### ISSUE TITLE
Driver not working with kdmapper

### ISSUE THREAD

**Issue by 7AM7** [NMan1/OverflowRust#1]
> kdmapper.exe OverflowDriver.sys
[<] Loading vulnerable driver
[+] Image base has been allocated at 0xFFFFCD0A633BD000

Why It's stopped here ??

**Comment by 7AM7** [comment]
It’s working no but Pc crash when running the hack!! I am using kdmapper..

**Comment by NMan1** [comment]
You clearly have no idea what your doing. You have 2 options 

1. You can continue to try to get this work and If you somehow manage to figure out how to use this you will be instantly banned. 

2. You can go learn c++ and game hacking (cheating on rust is one of the hardest games, not for beginners). And then come back and use this as a LEARNING resource.
